name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test
        AIRTABLE_API_KEY: valid_airtable_api_key_123456789
        AIRTABLE_BASE_ID: test_base
        SLACK_CLIENT_ID: mock_client_id_value
        SLACK_CLIENT_SECRET: mock_client_secret_value
        SLACK_SIGNING_SECRET: mock_signing_secret_value
        SESSION_SECRET: mocksessionsecret32charsfortestX
        APP_BASE_URL: http://localhost:3000
        CALENDAR_FEED_TOKEN: mock_calendar_feed_token_value

    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        AIRTABLE_API_KEY: valid_airtable_api_key_123456789
        AIRTABLE_BASE_ID: test_base
        SLACK_CLIENT_ID: mock_client_id_value
        SLACK_CLIENT_SECRET: mock_client_secret_value
        SLACK_SIGNING_SECRET: mock_signing_secret_value
        SESSION_SECRET: mocksessionsecret32charsfortestX
        APP_BASE_URL: http://localhost:3000
        CALENDAR_FEED_TOKEN: mock_calendar_feed_token_value

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false